HotelPlus/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, pdf, Facture
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("facture/", Facture.as_view(), name="facture"),
    path("pdf/", pdf, name="pdf"),
    path("users/", include("users.urls")),
    path("chambre/", include("chambre.urls")),
    path("reservation", include("reservation.urls")),
    path("resto/", include("resto.urls")),
    path("config/", include("configuration.urls")),
    path("stats/", include("statistique.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chambre/urls.py
from django.urls import path
from .views import chambre_view, liste_chambre

urlpatterns = [
    path('add/', chambre_view, name='chambre'),
    path('', liste_chambre, name='liste_chambre'),
]

resto/urls.py
from django.urls import path

from resto.views import CreateMenu, ListMenu, UpdateMenu, DeleteMenu

urlpatterns = [
    path("", ListMenu.as_view(), name="home-resto"),
    path("add-menu/", CreateMenu.as_view(), name="add-menu"),
    path("update-menu/<int:id>", UpdateMenu.as_view(), name="update-menu"),
    path("delete-menu/<int:id>", DeleteMenu.as_view(), name="delete-menu"),
]

chambre/models.py
from django.db import models

# Create your models here.


class Chambre(models.Model):
    numero_chambre = models.CharField(max_length=10, null=True, unique=True)
    TYPE_CHOICES = [
        ('simple', 'Simple'),
        ('double', 'Double'),
    ]
    ETAT_CHOICES = [
        ('libre', 'Libre'),
        ('occupee', 'Occupée'),
    ]
    type_chambre = models.CharField(max_length=10, null=True, choices=TYPE_CHOICES)
    STATUT_CHOICES = [
        ('sale', 'Sale'),
        ('propre', 'Propre'),
    ]
    statut = models.CharField(max_length=10, null=True, choices=STATUT_CHOICES)
    etat = models.CharField(max_length=10, null=False, choices=ETAT_CHOICES)
    prix = models.DecimalField(max_digits=6, decimal_places=2)
    date = models.DateField(null=True)

chambre/forms.py
from .models import Chambre
from django import forms


class ChambreForm(forms.ModelForm):
    class Meta:
        model = Chambre
        fields = ['numero_chambre', 'type_chambre', 'statut', 'prix', 'date', 'etat']
        labels = {
            'numero_chambre': 'Numéro de chambre',
            'type_chambre': 'Type de chambre',
            'statut': 'Statut',
            'prix': 'Prix',
            'date': 'Date',
            'etat': 'Etat'
        }
        widgets = {
            'numero_chambre': forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 300px'}),
            'type_chambre': forms.Select(attrs={'class': 'form-control', 'style': 'width: 300px'}),
            'statut': forms.Select(attrs={'class': 'form-control', 'style': 'width: 300px'}),
            'prix': forms.NumberInput(attrs={'class': 'form-control', 'style': 'width: 300px'}),
            'date': forms.DateInput(attrs={'class': 'form-control', 'style': 'width: 300px'}),
            'etat': forms.Select(attrs={'class': 'form-control', 'style': 'width: 300px'}),

        }
        error_messages = {
            'numero_chambre': {
                'required': 'Veuillez fournir un numéro de chambre.',
            },
            'type_chambre': {
                'required': 'Veuillez sélectionner un type de chambre.',
            },
            'statut': {
                'required': 'Veuillez sélectionner un statut.',
            },
            'prix': {
                'required': 'Veuillez fournir un prix.',
                'invalid': 'Veuillez fournir un prix valide.',
            },
            'date': {
                'required': 'Veuillez fournir une date.',
                'invalid': 'Veuillez fournir une date valide.',
            },
        }

chambre/views.py
from django.shortcuts import render, redirect
from .forms import ChambreForm
from .models import Chambre
# Create your views here.


def chambre_view(request):
    if request.method == 'POST':
        form = ChambreForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/liste_chambre')
    else:
        form = ChambreForm()
    return render(request, 'chambre/chambre.html', {'form': form})



def liste_chambre(request):
    chambre = Chambre.objects.all()
    return render(request, 'chambre/liste_chambre.html', {'chambres': chambre})

chambre/templates/chambre/chambre.html
{% extends "base.html" %}
{% block title %}chambre{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center orange">Chambre</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Ajouter</button>
        </form>
    </div>
{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

chambre/templates/chambre/liste_chambre.html
{% extends "base.html" %}

{% block title %}list-chambre{% endblock %}

{% block content %}
    <div class="container">
         <div class="d-flex justify-content-center align-items-center my-2">
            <a href="{% url 'chambre' %}" class="btn btn-success text-center">Nouvelle Chambre</a>
        </div>
        <h1 class="text-center orange">Liste des chambres</h1>
        <table class="table table-striped table-dark">
            <thead>
                <tr>
                    <th>Numéro de chambre</th>
                    <th>Type de chambre</th>
                    <th>Statut</th>
                    <th>Prix</th>
                    <th>Date</th>
                    <th>Etat</th>
                </tr>
            </thead>
            <tbody>
                {% for chambre in chambres %}
                    <tr>
                        <td>{{ chambre.numero_chambre }}</td>
                        <td>{{ chambre.get_type_chambre_display }}</td>
                        <td>{{ chambre.get_statut_display }}</td>
                        <td>{{ chambre.prix }}</td>
                        <td>{{ chambre.date }}</td>
                        <td class="text-white{% if chambre.etat == 'libre' %}chambre-libre{% else %}chambre-occupee{% endif %}">
                            {{ chambre.get_etat_display }}
                        </td>
                        
                    </tr>
                    
                {% empty %}
                    <tr>
                        <td colspan="4">Aucune chambre disponible.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
{% endblock %}