HotelPlus/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, pdf, Facture
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("facture/", Facture.as_view(), name="facture"),
    path("pdf/", pdf, name="pdf"),
    path("users/", include("users.urls")),
    path("chambre/", include("chambre.urls")),
    path("reservation", include("reservation.urls")),
    path("resto/", include("resto.urls")),
    path("config/", include("configuration.urls")),
    path("stats/", include("statistique.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

configuration/urls.py
from django.urls import path

from configuration.views import home_config, CreateConfig, DetailConfig, ListConfig, regle_prix, ListRegle, update_config, \
    UpdateConfig, update_rule, delete_rule

app_name = "confighotel"
urlpatterns = [
    path("", home_config, name="home-config"),
    path("create-rule/", regle_prix, name="create-rule"),
    path("list-rule/", ListRegle.as_view(), name="list-rule"),
    path("update-rule/<int:id>", update_rule, name="update-rule"),
    path("delete-rule/<int:id>", delete_rule, name="delete-rule"),
    path("create/", CreateConfig.as_view(), name="create-config"),
    path("list/", ListConfig.as_view(), name="list-config"),
    path("detail/<int:pk>", DetailConfig.as_view(), name="detail-config"),
    path("update-config/<int:pk>", UpdateConfig.as_view(), name="update-config"),
    path("update-config/", update_config, name="update-config"),
]

resto/urls.py
from django.urls import path

from resto.views import CreateMenu, ListMenu, UpdateMenu, DeleteMenu

urlpatterns = [
    path("", ListMenu.as_view(), name="home-resto"),
    path("add-menu/", CreateMenu.as_view(), name="add-menu"),
    path("update-menu/<int:id>", UpdateMenu.as_view(), name="update-menu"),
    path("delete-menu/<int:id>", DeleteMenu.as_view(), name="delete-menu"),
]

configuration/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class Configuration(models.Model):
    nom = models.CharField(max_length=100)
    telephone = models.CharField(max_length=100, blank=True)
    adresse = models.CharField(max_length=200, blank=True)
    image = models.ImageField(upload_to="Logo", blank=True, null=True)
    date_ajout = models.DateField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("confighotel:detail-config", kwargs={"pk": self.pk})

    def __str__(self):
        return self.nom


class Categories(models.Model):
    CLASSES_CHAMBRES = (
        ("Classe A", "classe A"),
        ("Classe B", "classe B"),
        ("Classe C", "classe C"),
        ("Classe VIP", "VIP")
    )
    categorie = models.CharField(max_length=150, choices=CLASSES_CHAMBRES)
    prix_enfant = models.FloatField(default=0.0)
    prix_adulte = models.FloatField(default=0.0)

    class Meta:
        verbose_name = ("Categorie")
        verbose_name_plural = ("Categories")

    def __str__(self):
        return self.categorie

configuration/views.py
from django.forms import formset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, UpdateView, DetailView, ListView

from configuration.form import ConfigForm, ReglePrixForm
from configuration.models import Configuration, Categories


# Create your views here.


def home_config(request):
    return render(request, "confighotel/home.html")


def regle_prix(request):
    #ReglePrixFormset = formset_factory(ReglePrixForm, extra=4)
    #formset = ReglePrixFormset()
    form = ReglePrixForm()
    if request.method == "POST":
        form = ReglePrixForm(request.POST)
        #formset = ReglePrixFormset(request.POST or None)
        #formset = ReglePrixFormset(request.POST or None)
        #for form in formset:
        if form.is_valid():
            form.save()
            return redirect("confighotel:home-config")
    return render(request, "confighotel/create_rules.html", context={"form": form})


def update_rule(request, id):
    obj = get_object_or_404(Categories, id=id)
    if request.method == "POST":
        form = ReglePrixForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect("confighotel:list-rule")
    else:
        form = ReglePrixForm(instance=obj)

    return render(request, "confighotel/update_rule.html", {"form": form})


def delete_rule(request, id):
    regle = get_object_or_404(Categories, id=id)
    if request.method == "POST":
        regle.delete()
        return redirect("confighotel:list-rule")
    return render(request, "confighotel/delete_rule.html")


class CreateConfig(CreateView):
    form_class = ConfigForm
    template_name = "confighotel/add.html"
    queryset = Configuration.objects.all()

    # success_url = "home-config"

    def form_valid(self, form):
        return super().form_valid(form)


class ListConfig(ListView):
    template_name = "confighotel/list_config.html"
    queryset = Configuration.objects.all()


class ListRegle(ListView):
    template_name = "confighotel/list_regle.html"
    queryset = Categories.objects.all()


class DetailConfig(DetailView):
    template_name = "confighotel/detail_config.html"
    queryset = Configuration.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Configuration, pk=id_)


class UpdateConfig(UpdateView):
    form_class = ConfigForm
    template_name = "confighotel/add.html"
    queryset = Configuration.objects.all()


def update_config(request):
    last = Configuration.objects.all().count()
    obj = Configuration.objects.get(id=last)
    form = ConfigForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect("confighotel:detail-config")
    return render(request, "confighotel/add.html", {"form": form})

configuration/templates/confighotel/add.html
{% extends 'base.html' %}

{% block title %}add-chambre{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="form-group m-3">
                <div class="offset-md-2">
                    <form action="" method="post" enctype="multipart/form-data" class="form-control w-75 my-4">
                        <table>
                            {% csrf_token %}
                            {{ form.as_table }}
                        </table>
                        <input type="submit" value="Configurer" class="m-2 col-md-4 margin-left-input">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

configuration/templates/confighotel/create_rules.html
{% extends 'base.html' %}

{% block title %}create-rule-chambre{% endblock %}

{% block content %}
    <h2 class="text-center orange">Ajouter une nouvelle règle de prix</h2>
    <div class="container">
        <div class="row">
            <div class="form-group m-3">
                <div class="offset-md-2">
                    <form action="" method="post" class="form-control w-50">
                        <table>
                            {% csrf_token %}
                            {{ form.as_table }}
                        </table>
                        <input type="submit" value="creer" class="m-2 col-md-6 margin-left-input">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

configuration/templates/confighotel/delete_rule.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}
    <p>Êtes-vous sur de vouloir supprimer cette regle ? </p>
    <form method="post" action="">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Supprimer">
        <a class="btn btn-info" href="{% url 'confighotel:list-rule' %}">Retour</a>
    </form>
{% endblock %}

configuration/templates/confighotel/detail_config.html
{% extends 'base.html' %}

{% block title %}detail-chambre{% endblock %}

{% block content %}
    <img src="{{ object.image.url }}" class="logo">
    <h3>Nom Hotel : <a href="{% url 'confighotel:list-config' %}">{{ object.nom }}</a></h3>
    <p>Telephone  : {{ object.telephone }}</p>
    <p>Adresse    : {{ object.adresse }}</p>
    <a href="{% url 'confighotel:update-config' object.pk %}">Modifier</a>
{% endblock %}

configuration/templates/confighotel/home.html
{% extends 'base.html' %}

{% block title %}home-chambre{% endblock %}

{% block content %}
    <div class="row">
        <button class="col-sm-6 m-3 w-25"><a class="text-decoration-none" href="{% url 'confighotel:create-config' %}">Configuration</a></button>
        <button class="col-sm-6 m-3 w-25"><a class="text-decoration-none" href="{% url 'confighotel:create-rule' %}">Règle de prix</a></button>
        <button class="col-sm-6 m-3 w-25"><a class="text-decoration-none" href="{% url 'confighotel:list-config' %}">Voir configuration</a></button>
        <button class="col-sm-6 m-3 w-25"><a class="text-decoration-none" href="{% url 'confighotel:list-rule' %}">Voir règle de prix</a></button>
    </div>
{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

configuration/templates/confighotel/list_config.html
{% extends 'base.html' %}

{% block title %}list-chambre{% endblock %}

{% block content %}
    <h2>Voici la liste des configurations que vous avez fait pour votre hotel</h2>
    <div class="row">
        {% for object in object_list %}
            <div class="col-sm-4">
                <h3><a href="{{ object.get_absolute_url }}">{{ object.nom }}</a></h3>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

configuration/templates/confighotel/list_regle.html
{% extends 'base.html' %}

{% block title %}list-chambre{% endblock %}

{% block content %}
    <h2 class="text-center orange">Voici la liste des règles de prix pour votre hotel</h2>
    <div class="row">
        {% for object in object_list %}
            <div class="col-sm-6 my-3">
                <h3>CATEGORIE : <a href="{% url 'confighotel:home-config' %}">{{ object.categorie }}</a></h3>
                <p>
                    <span>PRIX ENFANT : {{ object.prix_enfant }}</span><br>
                    <span>PRIX ADULTE : {{ object.prix_adulte }}</span>
                </p>
                <a href="{% url 'confighotel:update-rule' object.id %}">Modifier la règle</a>
                <a href="{% url 'confighotel:delete-rule' object.id %}">Supprimer la règle</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

configuration/templates/confighotel/update_rule.html
{% extends 'base.html' %}

{% block title %}add-chambre{% endblock %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Modifier</button>
    </form>
{% endblock %}