HotelPlus/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, pdf, Facture
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("facture/", Facture.as_view(), name="facture"),
    path("pdf/", pdf, name="pdf"),
    path("users/", include("users.urls")),
    path("chambre/", include("chambre.urls")),
    path("reservation", include("reservation.urls")),
    path("resto/", include("resto.urls")),
    path("config/", include("configuration.urls")),
    path("stats/", include("statistique.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

configuration/urls.py
from django.urls import path

from configuration.views import home_config, CreateConfig, DetailConfig, ListConfig, regle_prix, ListRegle, update_config, \
    UpdateConfig, update_rule, delete_rule

app_name = "confighotel"
urlpatterns = [
    path("", home_config, name="home-config"),
    path("create-rule/", regle_prix, name="create-rule"),
    path("list-rule/", ListRegle.as_view(), name="list-rule"),
    path("update-rule/<int:id>", update_rule, name="update-rule"),
    path("delete-rule/<int:id>", delete_rule, name="delete-rule"),
    path("create/", CreateConfig.as_view(), name="create-config"),
    path("list/", ListConfig.as_view(), name="list-config"),
    path("detail/<int:pk>", DetailConfig.as_view(), name="detail-config"),
    path("update-config/<int:pk>", UpdateConfig.as_view(), name="update-config"),
    path("update-config/", update_config, name="update-config"),
]

resto/urls.py
from django.urls import path

from resto.views import CreateMenu, ListMenu, UpdateMenu, DeleteMenu

urlpatterns = [
    path("", ListMenu.as_view(), name="home-resto"),
    path("add-menu/", CreateMenu.as_view(), name="add-menu"),
    path("update-menu/<int:id>", UpdateMenu.as_view(), name="update-menu"),
    path("delete-menu/<int:id>", DeleteMenu.as_view(), name="delete-menu"),
]

users/urls.py
from django.urls import path
from .views import inscription, connexion, deconnexion, home

urlpatterns = [
    path("inscription/", inscription, name="inscription"),
    path("connexion/", connexion, name="connexion"),
    path("home/", home, name="home-users"),
    path("deconnexion", deconnexion, name="deconnexion"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class Users(AbstractUser):
    image_profile = models.ImageField()

    def __str__(self):
        return self.first_name


class Personnel(models.Model):
    FONCTION_CHOICES = (
        ('receptionniste', 'Réceptionniste'),
        ('menagere', 'Ménagère'),
        ('caissiere', 'Caissier(e)'),
        ('responsable', 'Responsable'),
        ('stagiaire', 'Stagiaire'),
        ('autre', 'Autre'),
    )

    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    telephone = models.CharField(max_length=20)
    email = models.EmailField()
    mot_de_passe = models.CharField(max_length=100)
    adresse = models.CharField(max_length=200)
    fonction = models.CharField(max_length=100, choices=FONCTION_CHOICES)
    date_inscription = models.DateField(null=True)
    date_expiration = models.DateField(null=True)

    class Meta:
        verbose_name = ("Personnel")
        verbose_name_plural = ("Personnels")

    def __str__(self):
        return self.nom + ' ' + self.prenom

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .formulaire import InscriptionForm, ConnexionForm

# Create your views here.


def inscription(request):
    form = InscriptionForm()
    if request.method == "POST":
        form = InscriptionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("connexion")
        else:
            form = InscriptionForm()
    return render(request, "users/inscription.html", context={"form":form})


def connexion(request):
    form = ConnexionForm()
    message = ""
    if request.method == "POST":
        form = ConnexionForm(request, data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data["username"], password=form.cleaned_data["password"])
            if user is not None and user.is_active and user.is_staff:
                login(request, user)
                return redirect("admin:index")
            else:
                login(request, user)
                return redirect("home-users")
        else:
            message = "Erreur d'identification"
    return render(request, "users/connexion.html", context={"form":form, "message":message})


@login_required
def home(request):
    return render(request, "users/home.html")


@login_required
def deconnexion(request):
    logout(request)
    return redirect("index")

users/templates/users/connexion.html
{% extends "base.html" %}

{% block title %}connexion{% endblock %}

{% block content %}
    <section class="login">
        <h1 class="text-center orange">Page de connexion</h1>
        <div class="error">
            {{ message }}
        </div>
        <div class="container">
            <div class="row">
                <div class="form-group m-3">
                    <div class="offset-md-4">
                        <form action="" method="post" class="form-control w-50">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="m-2">
                                    {{ field.label_tag }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <input class="btn-form col-md-6" type="submit" value="se connecter">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

users/templates/users/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}home{% endblock %}
<!--<div>
    <img src="{#% static 'images/default_profile.png' %#}" alt="profile" class="img-profile" title="changer de profile">
    <span>Bienvenue à vous : {{ user.username }}</span>
</div>-->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="offset-md-1">
                <button class="col-4 m-3 w-25 border-0 shadow-lg mb-5 rounded"><a class="a-menu text-decoration-none text-white fs-5 fw-semibold" href="{% url 'home-users' %}"><img src="{% static 'images/home.png' %}" alt="Icône Réservation" style="width: 50px; height: 50px;"><br>Home</a></button>
                <button class="col-4 m-3 w-25 border-0 shadow-lg mb-5 rounded"><a class="a-menu text-decoration-none text-white fs-5 fw-semibold" href="{% url 'liste_reservation' %}"><img src="{% static 'images/booking.png' %}" alt="Icône Réservation" style="width: 50px; height: 50px;"><br>Réservation</a></button>
                <button class="col-4 m-3 w-25 border-0 shadow-lg mb-5 rounded"><a class="a-menu text-decoration-none text-white fs-5 fw-semibold" href="{% url 'liste_chambre' %}"><img src="{% static 'images/chambre.png' %}" alt="Icône Réservation" style="width: 50px; height: 50px;"><br>Chambres</a></button>
                <button class="col-4 m-3 w-25 border-0 shadow-lg mb-5 rounded"></i><a class="a-menu text-decoration-none text-white fs-5 fw-semibold" href="{% url 'home-resto' %}"><img src="{% static 'images/serveur.png' %}" alt="Icône Réservation" style="width: 50px; height: 50px;"><br>Service Resto</a></button>
                <button class="col-4 m-3 w-25 border-0 shadow-lg mb-5 rounded"><a class="a-menu text-decoration-none text-white fs-5 fw-semibold" href=""><img src="{% static 'images/revenu.png' %}" alt="Icône Réservation" style="width: 50px; height: 50px;"><br>Autre Revenue</a></button>
                <button class="col-4 m-3 w-25 border-0 shadow-lg mb-5 rounded"></i><a class="a-menu text-decoration-none text-white fs-5 fw-semibold" href=""><img src="{% static 'images/paiement.png' %}" alt="Icône Réservation" style="width: 50px; height: 50px;"><br>Paiement</a></button>
                <button class="col-4 m-3 w-25 border-0 shadow-lg mb-5 rounded"><a class="a-menu text-decoration-none text-white fs-5 fw-semibold" href="{% url 'home-stat' %}"><img src="{% static 'images/statistiques.png' %}" alt="Icône Réservation" style="width: 50px; height: 50px;"><br>Statistique</a></button>
                <button class="col-4 m-3 w-25 border-0 shadow-lg mb-5 rounded"><a class="a-menu text-decoration-none text-white fs-5 fw-semibold" href="{% url 'confighotel:home-config' %}"><img src="{% static 'images/parametres.png' %}" alt="Icône Réservation" style="width: 50px; height: 50px;"><br>Parametre</a></button>
                <button class="col-4 m-3 w-25 border-0 shadow-lg mb-5 rounded"></i><a class="a-menu text-decoration-none text-white fs-5 fw-semibold" href="{% url 'deconnexion' %}"><img src="{% static 'images/déconnecter.png' %}" alt="Icône Réservation" style="width: 50px; height: 50px;">Deconnexion</a></button>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

users/templates/users/inscription.html
{% extends "base.html" %}

{% block title %}inscription{% endblock %}

{% block content %}
    <section class="login">
        <h1 class="text-center orange">Page d'inscription</h1>
        <!--<div class="error">
            {% if form.errors %}
                {{ form.errors }}
            {% endif %}
        </div>
        -->
        <div class="container">
            <div class="row">
                <div class="form-group m-3">
                    <div class="offset-md-4">
                        <form action="" method="post" class="form-control w-50">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="m-2">
                                    {{ field.label_tag }}
                                    {% if field.name == 'password1' %}
                                        <input type="password" class="form-control" id="{{ field.id_for_label }}" name="{{ field.html_name }}">
                                      {% elif field.name == 'password2' %}
                                        <input type="password" class="form-control" id="{{ field.id_for_label }}" name="{{ field.html_name }}">
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                </div>
                                {% if field.errors %}
                                    <p>
                                        {{ field.errors.as_text }}
                                    </p>
                                {% endif %}
                            {% endfor %}
                            <input class="btn-form col-md-6" type="submit" value="S'inscrire">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}